export const categoriasEcoturismo = [
  {
    nombre: 'Naturaleza',
    imagen: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=85',
    icono: {
      paths: ['m8 3 4 8 5-5 5 15H2L8 3z'],
      acentos: [
        { tipo: 'circle', cx: 17, cy: 5, r: 2 },
        { tipo: 'path', d: 'M17 1.3v1.1' },
        { tipo: 'path', d: 'M20 2.6l-.8.8' },
        { tipo: 'path', d: 'M14 2.6l.8.8' },
      ],
    },
  },
  {
    nombre: 'Aventura',
    imagen: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=85',
    icono: {
      paths: [],
      circles: [{ cx: 12, cy: 12, r: 9 }],
      acentos: [{ tipo: 'path', d: 'M16.24 7.76l-2.12 6.36-6.36 2.12 2.12-6.36 6.36-2.12z' }],
    },
  },
  {
    nombre: 'Fotografía',
    imagen: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=900&q=85',
    icono: {
      rects: [{ x: 2.5, y: 7, width: 19, height: 13.5, rx: 3 }],
      paths: ['M8.5 7 10 4.5h4L15.5 7', 'M17.5 10.8h.01'],
      circles: [],
      acentos: [{ tipo: 'circle', cx: 12, cy: 13.2, r: 3.6 }],
    },
  },
  {
    nombre: 'Tours',
    imagen: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=85',
    icono: {
      rects: [{ x: 4, y: 3.5, width: 16, height: 12, rx: 2.5 }],
      paths: ['M7.5 15.5V18', 'M16.5 15.5V18'],
      circles: [{ cx: 8, cy: 18.6, r: 1.7 }, { cx: 16, cy: 18.6, r: 1.7 }],
      acentos: [{ tipo: 'path', d: 'M4 10h16' }],
    },
  },
  {
    nombre: 'Gastronomía',
    imagen: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=85',
    icono: {
      paths: [
        'M4 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2',
        'M7 2v20',
      ],
      acentos: [{ tipo: 'path', d: 'M21 15V2a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3zm0 0v7' }],
    },
  },
  {
    nombre: 'Eventos',
    imagen: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=900&q=85',
    icono: {
      rects: [{ x: 3, y: 4.5, width: 18, height: 16.5, rx: 2.5 }],
      paths: ['M16 2v4', 'M8 2v4'],
      acentos: [{ tipo: 'path', d: 'M3 9.5h18' }],
    },
  },
];

export const paquetesEcoturismo = [
  {
    categoria: 'Aventura',
    clase: '',
    imagen: `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura5.jpeg`,
    galeria: [
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura5.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura8.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura11.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura2.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura9.jpeg`,
    ],
    titulo: 'Adrenalina Serrana: Tierra & Cielo',
    socio: 'Manaure Aventura',
    socios: ['Manaure Aventura', 'Cuatri Tours Manaure', 'Villa Adelaida', 'La Casa de las Arepas'],
    ubicacion: 'Manaure, Cesar',
    duracion: '1 d\u00eda',
    precio: '$340.000',
    descripcion: '"Conquista el ca\u00f1\u00f3n del Perij\u00e1 volando entre nubes y rugiendo sobre cuatro ruedas." D\u00eda completo de parapente t\u00e1ndem y traves\u00eda en cuatrimoto 4x4 con almuerzo campestre y ba\u00f1o en el r\u00edo Manaure.',
    incluye: ['Vuelo t\u00e1ndem certificado con pilotos y video 4K', 'Cuatrimoto 4x4 con casco, gafas y gu\u00edas', 'Desayuno campesino y almuerzo campestre con bebida', 'Acceso al R\u00edo Manaure y piscina'],
    noIncluye: ['Souvenirs o compras personales.', 'Bebidas adicionales no incluidas.', 'Propinas voluntarias.'],
    itinerario: [
      { hora: '07:30 AM', titulo: 'Desayuno criollo', texto: 'Arepa de ch\u00f3colo con queso y caf\u00e9 de olla en La Casa de las Arepas.' },
      { hora: '08:45 AM', titulo: 'Vuelo en parapente', texto: 'Vuelo t\u00e1ndem biplaza sobre el ca\u00f1\u00f3n con Manaure Aventura y video 4K.' },
      { hora: '11:15 AM', titulo: 'Traves\u00eda en cuatrimotos 4x4', texto: 'Ruta guiada por trochas y Pozo Azul con Cuatri Tours Manaure.' },
      { hora: '01:30 PM', titulo: 'Almuerzo y r\u00edo Manaure', texto: 'Banquete campestre en Villa Adelaida y ba\u00f1o en pozas de agua viva.' },
    ],
  },
  {
    categoria: 'Tours',
    clase: 'blue',
    imagen: `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza3.jpeg`,
    galeria: [
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza3.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza4.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza5.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza11.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza12.jpeg`,
    ],
    titulo: 'Cumbres de Niebla & Romance',
    socio: 'Mashiramo Glamping',
    socios: ['Mashiramo Glamping', 'Absolom Casita de la Mora', 'Villa Adelaida'],
    ubicacion: 'Manaure, Cesar',
    duracion: '2 d\u00edas y 1 noche',
    precio: '$790.000',
    descripcion: '"Escapada \u00edntima a 2.400 m entre estrellas, domos geod\u00e9sicos y fuego." Incluye almuerzo especial en Villa Adelaida y noche en domo con jacuzzi. Precio de referencia por pareja.',
    incluye: ['1 noche en domo geod\u00e9sico en Mashiramo', '3 comidas campesinas y almuerzo especial en Villa Adelaida', 'Jacuzzi privado climatizado bajo las estrellas', 'C\u00f3ctel de bienvenida y vino de mora', 'Transporte 4x4 ida y regreso desde Manaure'],
    noIncluye: ['Souvenirs o compras personales.', 'Bebidas adicionales no incluidas.', 'Propinas voluntarias.'],
    itinerario: [
      { hora: 'D\u00eda 1 · 01:00 PM', titulo: 'Almuerzo en Villa Adelaida', texto: 'Chivo al curry o mojarra fresca en kiosco privado para dos.' },
      { hora: 'D\u00eda 1 · 03:00 PM', titulo: 'Torta de mora y vino', texto: 'Parada dulce en ABSOLOM: torta tibia de mora y vino de mora silvestre.' },
      { hora: 'D\u00eda 1 · 05:00 PM', titulo: 'Subida 4x4 a Mashiramo', texto: 'Check-in en domo con jacuzzi exterior y fogata con malvaviscos.' },
      { hora: 'D\u00eda 2 · 08:30 AM', titulo: 'Bosque de niebla', texto: 'Desayuno sobre las nubes y caminata por el sendero del Oso.' },
    ],
  },
  {
    categoria: 'Tours',
    clase: 'blue',
    imagen: `${process.env.PUBLIC_URL}/assets/galeria/Gastronomia/La casa de las arepas/gastronomia12.JPG`,
    galeria: [
      `${process.env.PUBLIC_URL}/assets/galeria/Gastronomia/La casa de las arepas/gastronomia12.JPG`,
      `${process.env.PUBLIC_URL}/assets/galeria/Gastronomia/La casa de las arepas/gastronomia8.jpg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza5.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura6.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza11.jpeg`,
    ],
    titulo: 'Ruta del Grano a la Fruta: Caf\u00e9 & Mora',
    socio: 'Coruscans',
    socios: ['Coruscans', 'Absolom Casita de la Mora', 'La Casa de las Arepas', 'Los Pinos Manaure'],
    ubicacion: 'Manaure, Cesar',
    duracion: '1 d\u00eda',
    precio: '$145.000',
    descripcion: '"El alma campesina: cosecha caf\u00e9 bajo sombra, recolecta moras y hornea tradici\u00f3n." D\u00eda de agroturismo familiar entre cafetales, miradores y dulces de mora.',
    incluye: ['Desayuno tradicional y almuerzo campesino de monta\u00f1a', 'Taller sensorial y cata de caf\u00e9 con barista', 'Canasto de moras reci\u00e9n cosechadas para llevar', 'Entradas a Los Pinos y degustaci\u00f3n en La Casita de la Mora'],
    noIncluye: ['Souvenirs o compras personales.', 'Bebidas adicionales no incluidas.', 'Propinas voluntarias.'],
    itinerario: [
      { hora: '08:00 AM', titulo: 'Desayuno de ma\u00edz', texto: 'Arepas reci\u00e9n asadas en le\u00f1a en La Casa de las Arepas con queso hilado.' },
      { hora: '09:30 AM', titulo: 'Taller de caf\u00e9 en El Coruscans', texto: 'Cosecha manual en cafetales bajo sombra y cata de caf\u00e9 serrano.' },
      { hora: '12:30 PM', titulo: 'Mirador Los Pinos y almuerzo', texto: 'Jard\u00edn bot\u00e1nico de arte topiario y almuerzo t\u00edpico.' },
      { hora: '02:30 PM', titulo: 'Cosecha de moras en ABSOLOM', texto: 'Recolecta tus propias moras y degustaci\u00f3n dulce.' },
    ],
  },
  {
    categoria: 'Naturaleza',
    clase: 'green',
    imagen: `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza2.jpeg`,
    galeria: [
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza2.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza6.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza9.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza1.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza13.jpeg`,
    ],
    titulo: 'Expedici\u00f3n Metallura: Joyas Aladas',
    socio: 'Metallura',
    socios: ['Metallura', 'Coruscans', 'Villa Adelaida'],
    ubicacion: 'Manaure, Cesar',
    duracion: '2 d\u00edas y 1 noche',
    precio: '$520.000',
    descripcion: '"Tras el rastro del colibr\u00ed del Perij\u00e1 en bosques de niebla y p\u00e1ramo." Expedici\u00f3n cient\u00edfica con orn\u00edtologo, visita a la Reserva ProAves y amanecer en Sabana Rubia.',
    incluye: ['Gu\u00eda ornit\u00f3logo profesional y telescopio', 'Pr\u00e9stamo de binoculares HD y checklist de aves', 'Alojamiento de monta\u00f1a en la Reserva ProAves', 'Transporte 4x4 y comidas completas'],
    noIncluye: ['Equipo personal de monta\u00f1a.', 'Souvenirs o compras personales.', 'Propinas voluntarias.'],
    itinerario: [
      { hora: 'D\u00eda 1 · 06:30 AM', titulo: 'Salida en 4x4', texto: 'Pajareo en El Coruscans: colibr\u00edes, tangaras y fauna del gradiente medio.' },
      { hora: 'D\u00eda 1 · 11:30 AM', titulo: 'Reserva ProAves', texto: 'Ascenso a 2.800 m y rastreo con orn\u00edtologo de Metallura.' },
      { hora: 'D\u00eda 1 · 06:30 PM', titulo: 'Noche en eco-lodge', texto: 'Cena de monta\u00f1a y charla de conservaci\u00f3n con telescopio.' },
      { hora: 'D\u00eda 2 · 05:30 AM', titulo: 'Sabana Rubia', texto: 'P\u00e1ramo al amanecer entre frailejones y regreso a Villa Adelaida.' },
    ],
  },
  {
    categoria: 'Tours',
    clase: 'blue',
    imagen: `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura2.jpeg`,
    galeria: [
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura2.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura9.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura11.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza5.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura3.jpeg`,
    ],
    titulo: 'Pasad\u00eda Oasis Familiar: Aguas Vivas',
    socio: 'Villa Adelaida',
    socios: ['Villa Adelaida', 'Los Pinos Manaure'],
    ubicacion: 'Manaure, Cesar',
    duracion: '1 d\u00eda',
    precio: '$115.000',
    descripcion: '"D\u00eda de sol, naturaleza y r\u00edo refrescante para grandes y chicos." Pasad\u00eda con piscina, parque Los Pinos, pozas del Balneario R\u00edo Manaure y sancocho a la le\u00f1a. Precio de referencia por adulto.',
    incluye: ['Acceso total a piscina, zonas verdes y quioscos', 'Entrada al parque Los Pinos y sesi\u00f3n fotogr\u00e1fica libre', 'Almuerzo criollo completo a la le\u00f1a', 'Pr\u00e9stamo de flotadores y postre regional'],
    noIncluye: ['Souvenirs o compras personales.', 'Bebidas adicionales no incluidas.', 'Propinas voluntarias.'],
    itinerario: [
      { hora: '08:30 AM', titulo: 'Bienvenida en Villa Adelaida', texto: 'Jugo de corozo o mora en quiosco campestre.' },
      { hora: '09:30 AM', titulo: 'Aventura en Los Pinos', texto: 'Dinosaurios y animales gigantes podados en cipreses.' },
      { hora: '11:30 AM', titulo: 'Ba\u00f1o en el R\u00edo Manaure', texto: 'Pozas cristalinas del Balneario con flotadores y chalecos.' },
      { hora: '01:00 PM', titulo: 'Sancocho a la le\u00f1a', texto: 'Almuerzo campesino, piscina de manantial y hamacas.' },
    ],
  },
  {
    categoria: 'Fotograf\u00eda',
    clase: '',
    imagen: `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza6.jpeg`,
    galeria: [
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza6.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza2.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza9.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza7.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza1.jpeg`,
    ],
    titulo: 'Safari Fotogr\u00e1fico: Nidos & Hora Dorada',
    socio: 'PHOTours',
    socios: ['PHOTours', 'Los Pinos Manaure', 'Absolom Casita de la Mora', 'Villa Adelaida'],
    ubicacion: 'Manaure, Cesar',
    duracion: '1 d\u00eda',
    precio: '$290.000',
    descripcion: '"Captura postales \u00e9picas con vestidos flotantes, columpio al vac\u00edo y cascadas secretas." D\u00eda con fot\u00f3grafo profesional, de la bruma matinal a la hora dorada.',
    incluye: ['Fot\u00f3grafo profesional todo el recorrido', 'Pr\u00e9stamo de vestido de gala flotante y accesorios', '15 fotos editadas en alta definici\u00f3n', 'Entradas a locaciones privadas y almuerzo gourmet'],
    noIncluye: ['Vestidos adicionales personalizados.', 'Souvenirs o compras personales.', 'Propinas voluntarias.'],
    itinerario: [
      { hora: '06:00 AM', titulo: 'Bruma en Los Pinos', texto: 'Contraluces en el laberinto de cipreses y desayuno criollo.' },
      { hora: '10:00 AM', titulo: 'Cascadas secretas', texto: 'Sesi\u00f3n con PHOTours en pozos esmeralda.' },
      { hora: '01:30 PM', titulo: 'Almuerzo en Villa Adelaida', texto: 'Gastronom\u00eda criolla y descanso junto al r\u00edo.' },
      { hora: '04:00 PM', titulo: 'Columpio al infinito', texto: 'Golden hour sobre la cordillera y brindis en ABSOLOM.' },
    ],
  },
  {
    categoria: 'Gastronom\u00eda',
    clase: '',
    imagen: `${process.env.PUBLIC_URL}/assets/galeria/Gastronomia/La casa de las arepas/gastronomia8.jpg`,
    galeria: [
      `${process.env.PUBLIC_URL}/assets/galeria/Gastronomia/La casa de las arepas/gastronomia8.jpg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Gastronomia/La casa de las arepas/gastronomia12.JPG`,
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura6.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza5.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza11.jpeg`,
    ],
    titulo: 'Sabores del Perij\u00e1: Ruta Culinaria',
    socio: 'La Casa de las Arepas',
    socios: ['La Casa de las Arepas', 'Coruscans', 'Villa Adelaida', 'Absolom Casita de la Mora'],
    ubicacion: 'Manaure, Cesar',
    duracion: '1 d\u00eda',
    precio: '$175.000',
    descripcion: '"Del ma\u00edz en brasas a los sancochos criollos, el caf\u00e9 serrano y la mora." Circuito de 4 estaciones con cocineros locales de Manaure.',
    incluye: ['4 tiempos de comida y degustaciones de autor', 'Cata guiada por barista profesional', 'Transporte guiado entre estaciones', 'Charla y recetas con cocineros locales'],
    noIncluye: ['Platos fuera del men\u00fa del plan.', 'Bebidas adicionales no incluidas.', 'Propinas voluntarias.'],
    itinerario: [
      { hora: 'Estaci\u00f3n 1', titulo: 'La Casa de las Arepas', texto: 'Arepa perijanera con carne desmechada y queso hilado.' },
      { hora: 'Estaci\u00f3n 2', titulo: 'Caf\u00e9 El Coruscans', texto: 'Cata de 3 perfiles de caf\u00e9 especial con queso de hoja.' },
      { hora: 'Estaci\u00f3n 3', titulo: 'Villa Adelaida', texto: 'Chivo al curry, arroz de coco y sopa de malangada.' },
      { hora: 'Estaci\u00f3n 4', titulo: 'ABSOLOM La Casita de la Mora', texto: 'Torta tibia de mora, queso criollo y vino silvestre.' },
    ],
  },
  {
    categoria: 'Aventura',
    clase: '',
    imagen: `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura7.jpeg`,
    galeria: [
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura7.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura10.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura4.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura1.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura6.jpeg`,
    ],
    titulo: 'Traves\u00eda Sabana Rubia: P\u00e1ramo M\u00edstico',
    socio: 'Metallura',
    socios: ['Metallura', 'Mashiramo Glamping', 'Villa Adelaida'],
    ubicacion: 'Manaure, Cesar',
    duracion: '1 d\u00eda',
    precio: '$280.000',
    descripcion: '"Supera los 3.200 metros caminando entre frailejones en el techo del Cesar." Trekking exigente con gu\u00eda de alta monta\u00f1a e hidroterapia final en el r\u00edo.',
    incluye: ['Transporte 4x4 de monta\u00f1a ida y regreso', 'Gu\u00eda de alta monta\u00f1a, botiqu\u00edn y radio', 'Desayuno caliente y almuerzo picnic', 'Seguro m\u00e9dico y bastones de trekking'],
    noIncluye: ['Equipo personal de monta\u00f1a.', 'Souvenirs o compras personales.', 'Propinas voluntarias.'],
    itinerario: [
      { hora: '04:30 AM', titulo: 'Salida en 4x4', texto: 'Ascenso desde Villa Adelaida hacia las cumbres.' },
      { hora: '06:30 AM', titulo: 'Desayuno en Mashiramo', texto: 'Caldo campesino y caf\u00e9 org\u00e1nico para aclimatar.' },
      { hora: '08:00 AM', titulo: 'Trekking en Sabana Rubia', texto: 'P\u00e1ramo de frailejones y crestas de la serran\u00eda.' },
      { hora: '04:30 PM', titulo: 'Hidroterapia en Villa Adelaida', texto: 'Ba\u00f1o en aguas vivas para recuperaci\u00f3n muscular.' },
    ],
  },
  {
    categoria: 'Tours',
    clase: 'blue',
    imagen: `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza13.jpeg`,
    galeria: [
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza13.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza4.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza8.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza5.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza10.jpeg`,
    ],
    titulo: 'Bienestar & Desconexi\u00f3n: Monta\u00f1a Zen',
    socio: 'Coruscans',
    socios: ['Coruscans', 'Los Pinos Manaure', 'Villa Adelaida'],
    ubicacion: 'Manaure, Cesar',
    duracion: '2 d\u00edas y 1 noche',
    precio: '$390.000',
    descripcion: '"Inmersi\u00f3n en agua viva, aromaterapia de cafetales y descanso reparador." Retiro wellness con caba\u00f1a t\u00e9rmica, caminatas conscientes e hidroterapia.',
    incluye: ['1 noche en caba\u00f1a campestre privada', 'Alimentaci\u00f3n consciente campesina completa', 'Hidroterapia natural en el r\u00edo Manaure', 'Infusiones herbales y caf\u00e9 de altura ilimitado'],
    noIncluye: ['Tratamientos de spa externos.', 'Souvenirs o compras personales.', 'Propinas voluntarias.'],
    itinerario: [
      { hora: 'D\u00eda 1 · 10:00 AM', titulo: 'Check-in en El Coruscans', texto: 'Caba\u00f1a t\u00e9rmica entre nogales y cafetales.' },
      { hora: 'D\u00eda 1 · 11:30 AM', titulo: 'Caminata descalza', texto: 'Conexi\u00f3n a tierra en el cafetal y t\u00e9 org\u00e1nico.' },
      { hora: 'D\u00eda 1 · 04:00 PM', titulo: 'Niebla en Los Pinos', texto: 'Atardecer contemplativo en el mirador bot\u00e1nico.' },
      { hora: 'D\u00eda 2 · 10:00 AM', titulo: 'Hidroterapia en el r\u00edo', texto: 'Pozas cristalinas de Villa Adelaida y siesta en hamacas.' },
    ],
  },
  {
    categoria: 'Tours',
    clase: 'blue',
    imagen: `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura3.jpeg`,
    galeria: [
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura3.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza10.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza11.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/aventura/Manaure-aventuras/aventura8.jpeg`,
      `${process.env.PUBLIC_URL}/assets/galeria/Naturaleza/Metallura/naturaleza4.jpeg`,
    ],
    titulo: 'Gran Circuito Manaure Vive 3D/2N',
    socio: 'Villa Adelaida',
    socios: ['Manaure Aventura', 'Villa Adelaida', 'Cuatri Tours Manaure', 'PHOTours', 'Mashiramo Glamping', 'Absolom Casita de la Mora', 'Coruscans', 'La Casa de las Arepas', 'Los Pinos Manaure', 'Metallura'],
    ubicacion: 'Valledupar y Manaure, Cesar',
    duracion: '3 d\u00edas y 2 noches',
    precio: '$1.350.000',
    descripcion: '"El pasaporte definitivo: vive los 10 aliados y todas las facetas del Balc\u00f3n del Cesar." Experiencia insignia VIP todo incluido con parapente, cuatrimotos, glamping y fiesta criolla.',
    incluye: ['Transporte privado 4x4 los 3 d\u00edas', '2 noches (Glamping Mashiramo + Caba\u00f1a El Coruscans)', 'Todas las comidas criollas', 'Parapente t\u00e1ndem con video 4K y cuatrimotos', 'Sesi\u00f3n fotogr\u00e1fica con 20 fotos editadas', 'Aviturismo, cata de caf\u00e9 y seguro m\u00e9dico total'],
    noIncluye: ['Gastos personales no especificados.', 'Bebidas adicionales no incluidas.', 'Propinas voluntarias.'],
    itinerario: [
      { hora: 'Viernes', titulo: 'R\u00edo, cuatris y glamping', texto: 'Almuerzo en Villa Adelaida, r\u00edo Manaure, 4x4 con Cuatritours y domo en Mashiramo con jacuzzi.' },
      { hora: 'S\u00e1bado', titulo: 'Aves, parapente y fotos', texto: 'Aviturismo con Metallura, parapente con Manaure Aventura, fotos en cascadas con PHOTours y noche en El Coruscans.' },
      { hora: 'Domingo', titulo: 'Topiarios, mora y fiesta', texto: 'Esculturas de Los Pinos, recolecci\u00f3n en ABSOLOM y banquete final con tr\u00edo vallenato.' },
    ],
  },
];


export const conveniosEcoturismo = [
  { nombre: 'Manaure Aventura', descripcion: 'Aventura y diversión', logo: 'manaure-aventura.webp', instagram: 'https://www.instagram.com/manaureaventura/' },
  { nombre: 'Villa Adelaida', descripcion: 'Naturaleza y descanso', logo: 'villa-adelaida.webp', instagram: 'https://www.instagram.com/villadelaidaturismo/' },
  { nombre: 'Cuatri Tours Manaure', descripcion: 'Paseos en cuatrimoto', logo: 'cuatri-tours-manaure.webp', instagram: 'https://www.instagram.com/cuatritoursmanaure/' },
  { nombre: 'PHOTours', descripcion: 'Fotografía y experiencias', logo: 'photours.webp', instagram: 'https://www.instagram.com/photours_col/' },
  { nombre: 'Mashiramo Glamping', descripcion: 'Alojamiento en la naturaleza', logo: 'mashiramo-glamping.webp', instagram: 'https://www.instagram.com/mashiramoglamping/' },
  { nombre: 'Absolom Casita de la Mora', descripcion: 'Hospedaje y naturaleza', logo: 'absolom-casita-de-la-mora.webp', instagram: 'https://www.instagram.com/absolomlacasitadelamora/' },
  { nombre: 'Coruscans', descripcion: 'Experiencias del territorio', logo: 'coruscans.webp', instagram: 'https://www.instagram.com/elcoruscans/' },
  { nombre: 'La Casa de las Arepas', descripcion: 'Gastronomía local', logo: 'la-casa-de-las-arepas.webp', instagram: 'https://www.instagram.com/lacasadelasarepasmanaure/' },
  { nombre: 'Los Pinos Manaure', descripcion: 'Descanso y experiencias', logo: 'los-pinos-manaure.webp', instagram: 'https://www.instagram.com/lospinosmanaure/' },
  { nombre: 'Metallura', descripcion: 'Naturaleza y aventura', logo: 'metallura.webp', instagram: 'https://www.instagram.com/metalluranature/' },
];

export const galeriaEcoturismo = [
  { imagen: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1100&q=85', alt: 'Paisaje natural de Manaure' },
  { imagen: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=85', alt: 'Sendero entre montañas' },
  { imagen: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=900&q=85', alt: 'Paisaje verde de la región' },
  { imagen: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=85', alt: 'Gastronomía local' },
  { imagen: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=85', alt: 'Personas compartiendo al aire libre' },
  { imagen: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85', alt: 'Paisaje abierto para descansar' },
];
