import { useState } from 'react';

export const whatsappUrl = 'https://wa.me/573012706114';

export const categorias = [
  'Pasadías',
  'Parejas',
  'Familia',
  'Naturaleza y aventura',
  'Alojamiento',
  'Eventos',
];

export const experiencias = [
  {
    categoria: 'Pasadías',
    imagen: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=1000&q=85',
    alt: 'Piscina rodeada de naturaleza para un pasadía',
    etiqueta: 'DÍA COMPLETO',
    nombre: 'Pasadía Villa Adelaida',
    descripcion: 'Experiencia de día completo con naturaleza, piscina, gastronomía y espacios para compartir.',
    duracion: 'Duración: día completo',
    precio: '$95.000',
    caracteristicas: ['Piscina', 'Naturaleza y río', 'Gastronomía típica regional'],
  },
  {
    categoria: 'Pasadías',
    imagen: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=85',
    alt: 'Paisaje natural para disfrutar un día de descanso',
    etiqueta: 'DESCANSO Y NATURALEZA',
    nombre: 'Pasadía Río y Naturaleza',
    descripcion: 'Un plan para disfrutar el paisaje, el río y la tranquilidad de Villa Adelaida durante el día.',
    duracion: 'Duración: día completo',
    precio: '$85.000',
    caracteristicas: ['Río', 'Naturaleza', 'Espacios para compartir'],
  },
  {
    categoria: 'Pasadías',
    imagen: 'https://images.unsplash.com/photo-1529543544282-ea669407fca3?auto=format&fit=crop&w=1000&q=85',
    alt: 'Mesa preparada para una experiencia gastronómica',
    etiqueta: 'SABOR DE LA VILLA',
    nombre: 'Pasadía Gastronómico',
    descripcion: 'Una jornada para combinar descanso, gastronomía típica regional y el ambiente natural de la Villa.',
    duracion: 'Duración: jornada completa',
    precio: '$110.000',
    caracteristicas: ['Gastronomía típica regional', 'Asados al carbón', 'Naturaleza'],
  },
  {
    categoria: 'Parejas',
    imagen: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1000&q=85',
    alt: 'Escapada romántica en un entorno natural',
    etiqueta: 'MOMENTO ESPECIAL',
    nombre: 'Noche Romántica',
    descripcion: 'Experiencia para parejas con un ambiente especial, naturaleza y tiempo para conectar.',
    duracion: 'Duración: una noche',
    precio: '$380.000',
    caracteristicas: ['Ambiente romántico', 'Gastronomía', 'Naturaleza'],
  },
  {
    categoria: 'Familia',
    imagen: 'https://images.unsplash.com/photo-1504150558240-0b4fd8946624?auto=format&fit=crop&w=1000&q=85',
    alt: 'Familia compartiendo en un espacio natural',
    etiqueta: 'PARA COMPARTIR',
    nombre: 'Día Familiar',
    descripcion: 'Un plan para disfrutar en familia con espacios de naturaleza, piscina y actividades para compartir.',
    duracion: 'Duración: día completo',
    precio: '$120.000',
    caracteristicas: ['Piscina', 'Juegos para niños', 'Gastronomía típica regional'],
  },
  {
    categoria: 'Familia',
    imagen: 'https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&w=1000&q=85',
    alt: 'Familia disfrutando un espacio de naturaleza',
    etiqueta: 'TIEMPO EN FAMILIA',
    nombre: 'Aventura Familiar',
    descripcion: 'Un día para explorar, jugar y compartir en contacto con la naturaleza y los espacios de la Villa.',
    duracion: 'Duración: día completo',
    precio: '$260.000',
    caracteristicas: ['Juegos para niños', 'Senderismo ecológico', 'Piscina'],
  },
  {
    categoria: 'Familia',
    imagen: 'https://images.unsplash.com/photo-1504150558240-0b4fd8946624?auto=format&fit=crop&w=1000&q=85',
    alt: 'Familia compartiendo una comida al aire libre',
    etiqueta: 'PARA COMPARTIR',
    nombre: 'Familia y Parrilla',
    descripcion: 'Una experiencia para reunirse alrededor de la gastronomía, los asados y un entorno tranquilo.',
    duracion: 'Duración: jornada completa',
    precio: '$65.000',
    caracteristicas: ['Parrilladas', 'Asados al carbón', 'Espacios familiares'],
  },
  {
    categoria: 'Naturaleza y aventura',
    imagen: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1000&q=85',
    alt: 'Sendero natural entre montañas y vegetación',
    etiqueta: 'CONEXIÓN NATURAL',
    nombre: 'Senderismo Ecológico',
    descripcion: 'Recorrido para descubrir el entorno natural, respirar aire puro y vivir una pausa activa.',
    duracion: 'Duración: media jornada',
    precio: '$95.000',
    caracteristicas: ['Senderismo ecológico', 'Naturaleza', 'Río'],
  },
  {
    categoria: 'Naturaleza y aventura',
    imagen: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?auto=format&fit=crop&w=1000&q=85',
    alt: 'Camping bajo un cielo natural',
    etiqueta: 'AL AIRE LIBRE',
    nombre: 'Camping',
    descripcion: 'Experiencia de conexión con la naturaleza para disfrutar el entorno con otro ritmo.',
    duracion: 'Duración: una noche',
    precio: '$260.000',
    caracteristicas: ['Camping', 'Naturaleza', 'Noche al aire libre'],
  },
  {
    categoria: 'Alojamiento',
    imagen: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1000&q=85',
    alt: 'Espacio de hospedaje rodeado de naturaleza',
    etiqueta: 'DESCANSO',
    nombre: 'Escapada Villa Adelaida',
    descripcion: 'Una pausa de descanso con hospedaje y la posibilidad de conectar con la naturaleza y el río.',
    duracion: 'Duración: fin de semana',
    precio: '$380.000',
    caracteristicas: ['Hospedaje', 'Naturaleza', 'Gastronomía'],
  },
  {
    categoria: 'Alojamiento',
    imagen: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1000&q=85',
    alt: 'Habitación de descanso para una escapada',
    etiqueta: 'ESCAPADA DE DESCANSO',
    nombre: 'Noche de Naturaleza',
    descripcion: 'Una noche de alojamiento para desconectarse y despertar cerca de los paisajes de Villa Adelaida.',
    duracion: 'Duración: una noche',
    precio: '$520.000',
    caracteristicas: ['Hospedaje', 'Naturaleza', 'Río'],
  },
  {
    categoria: 'Alojamiento',
    imagen: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=85',
    alt: 'Espacio acogedor para una estadía',
    etiqueta: 'ESTADÍA ESPECIAL',
    nombre: 'Fin de Semana en la Villa',
    descripcion: 'Una escapada para combinar alojamiento, gastronomía típica y experiencias de naturaleza.',
    duracion: 'Duración: fin de semana',
    precio: '$600.000',
    caracteristicas: ['Hospedaje', 'Gastronomía', 'Senderismo ecológico'],
  },
  {
    categoria: 'Eventos',
    imagen: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1000&q=85',
    alt: 'Espacio preparado para un evento',
    etiqueta: 'CELEBRACIONES',
    nombre: 'Eventos Villa Adelaida',
    descripcion: 'Espacios para celebraciones y reuniones con el ambiente natural y la sazón de Villa Adelaida.',
    duracion: 'Duración: según evento',
    precio: '$120.000',
    caracteristicas: ['Celebraciones', 'Música en vivo', 'Parrilladas y asados'],
  },
  {
    categoria: 'Eventos',
    imagen: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=85',
    alt: 'Celebración al aire libre',
    etiqueta: 'MOMENTOS ESPECIALES',
    nombre: 'Celebración al Aire Libre',
    descripcion: 'Un entorno natural para celebrar fechas especiales con familia, amigos o equipo de trabajo.',
    duracion: 'Duración: según evento',
    precio: '$450.000',
    caracteristicas: ['Eventos', 'Naturaleza', 'Música en vivo'],
  },
  {
    categoria: 'Eventos',
    imagen: 'https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1000&q=85',
    alt: 'Reunión compartida alrededor de una mesa',
    etiqueta: 'REUNIONES',
    nombre: 'Encuentro Villa Adelaida',
    descripcion: 'Espacios para reunirse, compartir una buena mesa y crear recuerdos en un ambiente diferente.',
    duracion: 'Duración: según evento',
    precio: '$140.000',
    caracteristicas: ['Reuniones', 'Gastronomía', 'Parrilladas'],
  },
  {
    categoria: 'Parejas',
    imagen: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1000&q=85',
    alt: 'Espacio de spa para descanso y bienestar',
    etiqueta: 'BIENESTAR',
    nombre: 'Spa',
    descripcion: 'Experiencia de descanso y bienestar para desconectarse de la rutina en un entorno natural.',
    duracion: 'Duración: jornada de bienestar',
    precio: '$120.000',
    caracteristicas: ['Spa', 'Descanso', 'Naturaleza'],
  },
  {
    categoria: 'Parejas',
    imagen: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1000&q=85',
    alt: 'Pareja disfrutando un momento especial',
    etiqueta: 'TIEMPO PARA DOS',
    nombre: 'Escapada para Dos',
    descripcion: 'Una pausa para disfrutar en pareja de la calma, la gastronomía y el entorno natural.',
    duracion: 'Duración: jornada o noche',
    precio: '$280.000',
    caracteristicas: ['Parejas', 'Naturaleza', 'Gastronomía'],
  },
  {
    categoria: 'Naturaleza y aventura',
    imagen: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85',
    alt: 'Actividad gastronómica alrededor del cacao',
    etiqueta: 'SABORES Y CULTURA',
    nombre: 'Experiencia del Cacao',
    descripcion: 'Actividad interactiva alrededor del cacao para conocer y disfrutar una tradición local.',
    duracion: 'Duración: media jornada',
    precio: '$120.000',
    caracteristicas: ['Experiencia interactiva del cacao', 'Naturaleza', 'Degustación'],
  },
];

export function useExperiencias() {
  const [categoriaActiva, setCategoriaActiva] = useState('Pasadías');
  const visibles = experiencias.filter(experiencia => experiencia.categoria === categoriaActiva);

  return { categoriaActiva, setCategoriaActiva, visibles };
}
